//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 008.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MY008TYPE                   129
#define IDD_SELECTFILE_PREVIEW          130
#define IDC_PICPREVIEW                  131
#define IDC_IMAGE_WIDTH                 132
#define IDC_IMAGE_HEIGHT                133
#define IDC_IMAGE_COLORBIT              134
#define IDC_IMAGE_FILESIZE              135
#define IDD_HISTOGRAM                   136
#define IDC_HISTOGRAM_CHANNEL           137
#define IDS_HISTOGRAM_SHOW              138
#define IDS_HISTOGRAM_CHANNEL           139
#define IDC_HISTO_RANGE                 140
#define IDC_HISTO_MID                   141
#define IDC_HISTO_PIXEL                 142
#define IDC_HISTO_COUNT                 143
#define IDC_HISTO_AVE                   144
#define IDC_HISTO_PERCENT               145
#define IDD_SAVE_IMAGEFILE              146
#define IDC_SAVEFILE_BITS_1             147
#define IDD_APP_SETTING                 147
#define IDC_SAVEFILE_BITS_4             148
#define IDC_SAVEFILE_BITS_8             149
#define IDC_SAVEFILE_BITS_16            150
#define IDC_SAVEFILE_BITS_24            151
#define IDC_SAVEFILE_BITS_32            152
#define IDC_SHOW_SAVE_QUALITY           153
#define IDC_SAVE_FILE_QUALITY           154
#define IDD_EFF_ADJUSTRGB               155
#define IDS_PICPREVIEW                  156
#define IDC_SHOWPARAM                   157
#define IDC_SHOWPARAM2                  158
#define IDC_SCROLL_PARAM                159
#define IDC_SCROLL_PARAM2               160
#define IDC_SHOWPARAM3                  161
#define IDC_SCROLL_PARAM3               162
#define IDC_EFF_RADIO1                  164
#define IDC_EFF_RADIO2                  165
#define IDC_EFF_RADIO3                  166
#define IDC_EFF_RADIO4                  167
#define IDD_EFF_ADJUSTHS                168
#define IDD_EFF_GAMMA                   169
#define IDD_EFF_COLORLEVEL              170
#define IDD_EFF_COLORBALANCE            171
#define IDC_EFF_CHECKBOX1               172
#define IDC_EFF_BUTTON1                 173
#define IDC_EFF_BUTTON2                 174
#define IDC_EFF_BUTTON3                 175
#define IDD_EFF_THRESHOLD               180
#define IDD_EFF_SOLARIZE                181
#define IDD_EFF_COLORTONE               182
#define IDC_COLOR_SELECT                183
#define IDB_COLORTONE_ARC               184
#define IDD_EFF_ADJUSTBRIGHTNESS        185
#define IDD_EFF_ADJUSTCONTRAST          186
#define IDD_EFF_NOISE                   188
#define IDD_EFF_NOISIFY                 189
#define IDD_EFF_OILPAINT                190
#define IDD_EFF_EMBOSS                  191
#define IDD_EFF_SPLASH                  192
#define IDD_EFF_POSTERIZE               193
#define IDD_EFF_SHIFT                   194
#define IDD_EFF_MOSAIC                  195
#define IDD_EFF_LENS                    196
#define IDD_EFF_STRIPE                  197
#define IDD_EFF_WHIRLPINCH              198
#define IDD_EFF_FRACTALTRACE            199
#define IDD_EFF_ILLUSION                200
#define IDD_EFF_RIPPLE                  201
#define IDD_EFF_WAVE                    202
#define IDD_EFF_DETECTEDGE              203
#define IDD_EFF_3DGRID                  204
#define IDC_3DGRID_SIZE                 205
#define IDC_3DGRID_DEPTH                206
#define IDD_EFF_FILLGRID                207
#define IDC_FILLGRID_WIDTH              208
#define IDC_FILLGRID_COLOR_1            209
#define IDC_FILLGRID_COLOR_2            210
#define IDD_EFF_CUSTOMFILTER            211
#define IDC_CUSTOM_FILTER0              212
#define IDC_CUSTOM_FILTER1              213
#define IDC_CUSTOM_FILTER2              214
#define IDC_CUSTOM_FILTER3              215
#define IDC_CUSTOM_FILTER4              216
#define IDC_CUSTOM_FILTER5              217
#define IDC_CUSTOM_FILTER6              218
#define IDC_CUSTOM_FILTER7              219
#define IDC_CUSTOM_FILTER8              220
#define IDC_CUSTOM_FILTER9              221
#define IDC_CUSTOM_FILTER10             222
#define IDC_CUSTOM_FILTER11             223
#define IDC_CUSTOM_FILTER12             224
#define IDC_CUSTOM_FILTER13             225
#define IDC_CUSTOM_FILTER14             226
#define IDC_CUSTOM_FILTER15             227
#define IDC_CUSTOM_FILTER16             228
#define IDC_CUSTOM_FILTER17             229
#define IDC_CUSTOM_FILTER18             230
#define IDC_CUSTOM_FILTER19             231
#define IDC_CUSTOM_FILTER20             232
#define IDC_CUSTOM_FILTER21             233
#define IDC_CUSTOM_FILTER22             234
#define IDC_CUSTOM_FILTER23             235
#define IDC_CUSTOM_FILTER24             236
#define IDC_CUSTOM_FILTER_SCALE         237
#define IDC_CUSTOM_FILTER_OFFSET        238
#define IDD_ADJUST_SIZE                 239
#define IDC_SIZE_RATIO                  240
#define IDC_SIZE_NEWWIDTH               241
#define IDC_SIZE_NEWHEIGHT              242
#define IDC_SIZE_SCALE_WIDTH            243
#define IDC_SIZE_SCALE_HEIGHT           244
#define IDC_STRETCH_NORMAL              245
#define IDC_STRETCH_BILINEAR            246
#define IDD_EFF_ROTATE                  247
#define IDD_EFF_BLINDS                  248
#define IDC_BK_COLOR                    249
#define IDD_EFF_VIDEO                   250
#define IDC_COMBO_PARAM                 251
#define IDD_LAYER_SMOOTHEDGE            253
#define IDD_EFF_AVERAGE_BLUR            254
#define IDD_EFF_GAUSS_BLUR              255
#define IDD_EFF_ZOOM_BLUR               256
#define IDD_EFF_RADIAL_BLUR             257
#define IDB_CLOTH_TEXTURE               258
#define IDD_EFF_INNERBEVEL_FRAME        260
#define IDD_EFF_LENSFLARE               261
#define IDD_EFF_TILEREFLECT             262
#define IDD_EFF_SOFTGLOW                263
#define IDC_UNDOLEVEL                   1000
#define ID_FILTER_START                 19000
#define ID_FILTER_INVERT                19001
#define ID_FILTER_ADJUSTRGB             19002
#define ID_FILTER_ADJUSTHS              19004
#define ID_FILTER_GAMMA                 19005
#define ID_FILTER_COLORLEVEL            19006
#define ID_FILTER_COLORBALANCE          19007
#define ID_FILTER_FLIP                  19008
#define ID_FILTER_MIRROR                19009
#define ID_FILTER_GRAYSCALE             19010
#define ID_FILTER_AUTO_COLORLEVEL       19011
#define ID_FILTER_AUTO_CONTRAST         19012
#define ID_FILTER_AUTO_COLORENHANCE     19013
#define ID_FILTER_DESPECKLE             19014
#define ID_FILTER_THRESHOLD             19015
#define ID_FILTER_SOLARIZE              19016
#define ID_FILTER_COLORTONE             19017
#define ID_FILTER_ADJUSTBRIGHTNESS      19018
#define ID_FILTER_ADJUSTCONTRAST        19019
#define ID_FILTER_NOISE                 19021
#define ID_FILTER_BLOT                  19022
#define ID_FILTER_OILPAINT              19023
#define ID_FILTER_EMBOSS                19024
#define ID_FILTER_SPLASH                19025
#define ID_FILTER_POSTERIZE             19026
#define ID_FILTER_SHIFT                 19027
#define ID_FILTER_CYLINDER              19028
#define ID_FILTER_MOSAIC                19029
#define ID_FILTER_LENS                  19030
#define ID_FILTER_STRIPE                19031
#define ID_FILTER_WHIRLPINCH            19032
#define ID_FILTER_FRACTALTRACE          19033
#define ID_FILTER_ILLUSION              19034
#define ID_FILTER_RIPPLE                19035
#define ID_FILTER_WAVE                  19036
#define ID_FILTER_HALFTONE              19037
#define ID_FILTER_DETECTEDGE            19038
#define ID_FILTER_3DGRID                19039
#define ID_FILTER_FILLGRID              19040
#define ID_FILTER_CUSTOMFILTER          19041
#define ID_FILTER_ROTATE90              19042
#define ID_FILTER_ROTATE270             19043
#define ID_FILTER_IMAGESIZE             19044
#define ID_FILTER_ROTATE                19045
#define ID_FILTER_BLINDS                19046
#define ID_FILTER_VIDEO                 19047
#define ID_FILTER_SMOOTH_EDGE           19049
#define ID_FILTER_ADD_SHADOW            19050
#define ID_FILTER_SHARP_LOW             19051
#define ID_FILTER_SHARP                 19052
#define ID_FILTER_SHARP_HIGH            19053
#define ID_FILTER_AVERAGE_BLUR          19056
#define ID_FILTER_GAUSS_BLUR            19057
#define ID_FILTER_ZOOM_BLUR             19058
#define ID_FILTER_RADIAL_BLUR           19059
#define ID_FILTER_CLOTH_TEXTURE         19060
#define ID_FILTER_INNERBEVEL_FRAME      19063
#define ID_FILTER_LENSFLARE             19065
#define ID_FILTER_SOFTGLOW              19066
#define ID_FILTER_TILEREFLECT           19067
#define ID_FILTER_END                   19999
#define ID_APP_SETTING                  20001
#define ID_HISTOGRAM                    20002
#define ID_FILTER_SAVE_ASCII            20003
#define ID_COUNT_COLOR                  20008
#define IDS_PICTURE_FORMAT              39000
#define IDS_SAVEFILE_FORMAT             39001
#define IDS_UNKNOW_IMAGE                39002
#define IDS_SAVEFILE_ERROR              39003
#define IDS_COPYTO_CLIPBOARD            39004
#define ID_ZOOM_IN                      39012
#define ID_ZOOM_ACTUAL                  39013
#define ID_ZOOM_OUT                     39014
#define IDS_INPUT_IMGSIZE_ZERO          39015
#define IDS_INPUT_IMGSIZE_LARGE         39016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         39048
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
